export const FETCH_USER = 'fetchUser';
// export const REGISTER_USER = 'registerUser';
export const SET_TOKEN = 'set_token';
export const FETCH_TRANSACTION_SUCCESS = 'fetchTransactionsSucces';
export const FETCH_NEAREST_SUCCES = 'slebewwww_nearest';
export const FETCH_CATEGORIES = 'heyaaa';
export const FETCH_ALL_DEVICES = 'Fetch_all';
export const FETCH_BY_FILTER = 'fetch_by_filterrr';
export const FETCH_HISTORY = 'fetch_history_succes';
export const baseUrl = "https://ad2d-139-192-36-123.ap.ngrok.io"